/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionsMenu: typeof import('./src/components/common/ActionsMenu.vue')['default']
    AddItem: typeof import('./src/components/items/AddItem.vue')['default']
    AddUserModal: typeof import('./src/components/admin/AddUserModal.vue')['default']
    AppearanceSetting: typeof import('./src/components/usersettings/AppearanceSetting.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    ChangePassword: typeof import('./src/components/usersettings/ChangePassword.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    DeleteAccount: typeof import('./src/components/usersettings/DeleteAccount.vue')['default']
    DeleteAlert: typeof import('./src/components/common/DeleteAlert.vue')['default']
    DeleteConfirmation: typeof import('./src/components/usersettings/DeleteConfirmation.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    EditItem: typeof import('./src/components/items/EditItem.vue')['default']
    EditUser: typeof import('./src/components/admin/EditUser.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Form: typeof import('@primevue/forms/form')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    NavBar: typeof import('./src/components/common/NavBar.vue')['default']
    NavigationComponent: typeof import('./src/components/menu/NavigationComponent.vue')['default']
    Password: typeof import('primevue/password')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    UserInformation: typeof import('./src/components/usersettings/UserInformation.vue')['default']
    UserMenu: typeof import('./src/components/menu/UserMenu.vue')['default']
    UserSettings: typeof import('./src/components/UserSettings.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
